language: node_js
node_js:
  - "10"

sudo: required

dist: trusty

before_install:
  - wget https://github.com/ethereum/solidity/releases/download/v0.5.13/solc-static-linux
  - chmod ugo+x solc-static-linux
  - sudo mv solc-static-linux /usr/bin/solc

install:
  - npm install
  - npm install -g eslint ethlint

script:
  - npm run eslint && npm run ethlint && npm run test

notifications:
  webhooks:
    urls:
      - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MG5pa2MlM0FtYXRyaXgub3JnLyUyMW5WVXBNWEN6VUhTY0tEQnNNQSUzQW1hdHJpeC5vcmc"
    on_success: change  # always|never|change
    on_failure: always
    on_start: never
